<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; ANOVA principles – r4nqy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./workflow.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ANOVA_how_it_works.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">ANOVA principles</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">r4nqy</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A recommended analysis workflow</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ANOVA_how_it_works.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">ANOVA principles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-is-anova" id="toc-what-is-anova" class="nav-link active" data-scroll-target="#what-is-anova"><span class="header-section-number">3.1</span> What is ANOVA?</a>
  <ul class="collapse">
  <li><a href="#the-basic-principles-of-anova" id="toc-the-basic-principles-of-anova" class="nav-link" data-scroll-target="#the-basic-principles-of-anova"><span class="header-section-number">3.1.1</span> The basic principles of ANOVA</a></li>
  <li><a href="#the-scenario" id="toc-the-scenario" class="nav-link" data-scroll-target="#the-scenario"><span class="header-section-number">3.1.2</span> The Scenario</a></li>
  <li><a href="#what-does-an-anova-do" id="toc-what-does-an-anova-do" class="nav-link" data-scroll-target="#what-does-an-anova-do"><span class="header-section-number">3.1.3</span> What does an ANOVA do?</a></li>
  <li><a href="#grand-mean" id="toc-grand-mean" class="nav-link" data-scroll-target="#grand-mean"><span class="header-section-number">3.1.4</span> Grand Mean</a></li>
  <li><a href="#measures-of-variability" id="toc-measures-of-variability" class="nav-link" data-scroll-target="#measures-of-variability"><span class="header-section-number">3.1.5</span> Measures of variability</a></li>
  <li><a href="#sst-ssf-sse" id="toc-sst-ssf-sse" class="nav-link" data-scroll-target="#sst-ssf-sse"><span class="header-section-number">3.1.6</span> SST = SSF + SSE</a></li>
  <li><a href="#partitioning-the-degrees-of-freedom" id="toc-partitioning-the-degrees-of-freedom" class="nav-link" data-scroll-target="#partitioning-the-degrees-of-freedom"><span class="header-section-number">3.1.7</span> Partitioning the degrees of freedom</a></li>
  <li><a href="#mean-squares" id="toc-mean-squares" class="nav-link" data-scroll-target="#mean-squares"><span class="header-section-number">3.1.8</span> Mean Squares</a></li>
  <li><a href="#f-ratios" id="toc-f-ratios" class="nav-link" data-scroll-target="#f-ratios"><span class="header-section-number">3.1.9</span> <em>F</em>-ratios</a></li>
  </ul></li>
  <li><a href="#anova-example-1" id="toc-anova-example-1" class="nav-link" data-scroll-target="#anova-example-1"><span class="header-section-number">3.2</span> ANOVA example 1</a></li>
  <li><a href="#anova-example-2" id="toc-anova-example-2" class="nav-link" data-scroll-target="#anova-example-2"><span class="header-section-number">3.3</span> ANOVA example 2</a>
  <ul class="collapse">
  <li><a href="#null-hypothesis" id="toc-null-hypothesis" class="nav-link" data-scroll-target="#null-hypothesis"><span class="header-section-number">3.3.1</span> Null hypothesis</a></li>
  <li><a href="#load-data-and-inspect-the-data" id="toc-load-data-and-inspect-the-data" class="nav-link" data-scroll-target="#load-data-and-inspect-the-data"><span class="header-section-number">3.3.2</span> Load data and inspect the data</a></li>
  <li><a href="#prepare-the-data" id="toc-prepare-the-data" class="nav-link" data-scroll-target="#prepare-the-data"><span class="header-section-number">3.3.3</span> Prepare the data</a></li>
  <li><a href="#plot-the-data" id="toc-plot-the-data" class="nav-link" data-scroll-target="#plot-the-data"><span class="header-section-number">3.3.4</span> Plot the data</a></li>
  <li><a href="#summarise-the-data" id="toc-summarise-the-data" class="nav-link" data-scroll-target="#summarise-the-data"><span class="header-section-number">3.3.5</span> Summarise the data</a></li>
  <li><a href="#way-anova" id="toc-way-anova" class="nav-link" data-scroll-target="#way-anova"><span class="header-section-number">3.3.6</span> 1-way ANOVA</a></li>
  <li><a href="#confidence-intervals-of-the-means" id="toc-confidence-intervals-of-the-means" class="nav-link" data-scroll-target="#confidence-intervals-of-the-means"><span class="header-section-number">3.3.7</span> Confidence intervals of the means</a></li>
  </ul></li>
  <li><a href="#anova-example-2-solution" id="toc-anova-example-2-solution" class="nav-link" data-scroll-target="#anova-example-2-solution"><span class="header-section-number">3.4</span> ANOVA example 2 solution</a>
  <ul class="collapse">
  <li><a href="#null-hypothesis-1" id="toc-null-hypothesis-1" class="nav-link" data-scroll-target="#null-hypothesis-1"><span class="header-section-number">3.4.1</span> Null hypothesis</a></li>
  <li><a href="#load-data-and-inspect-the-data-1" id="toc-load-data-and-inspect-the-data-1" class="nav-link" data-scroll-target="#load-data-and-inspect-the-data-1"><span class="header-section-number">3.4.2</span> Load data and inspect the data</a></li>
  <li><a href="#prepare-the-data-1" id="toc-prepare-the-data-1" class="nav-link" data-scroll-target="#prepare-the-data-1"><span class="header-section-number">3.4.3</span> Prepare the data</a></li>
  <li><a href="#plot-the-data-1" id="toc-plot-the-data-1" class="nav-link" data-scroll-target="#plot-the-data-1"><span class="header-section-number">3.4.4</span> Plot the data</a></li>
  <li><a href="#summarise-the-data-1" id="toc-summarise-the-data-1" class="nav-link" data-scroll-target="#summarise-the-data-1"><span class="header-section-number">3.4.5</span> Summarise the data</a></li>
  <li><a href="#way-anova-1" id="toc-way-anova-1" class="nav-link" data-scroll-target="#way-anova-1"><span class="header-section-number">3.4.6</span> 1-way ANOVA</a></li>
  <li><a href="#confidence-intervals-of-the-means-1" id="toc-confidence-intervals-of-the-means-1" class="nav-link" data-scroll-target="#confidence-intervals-of-the-means-1"><span class="header-section-number">3.4.7</span> Confidence intervals of the means</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">ANOVA principles</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Material used from Chapter One of Grafen and Hails: Modern Statistics for the Life Sciences</p>
<section id="what-is-anova" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="what-is-anova"><span class="header-section-number">3.1</span> What is ANOVA?</h2>
<section id="the-basic-principles-of-anova" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="the-basic-principles-of-anova"><span class="header-section-number">3.1.1</span> The basic principles of ANOVA</h3>
<p>In a simple case we consider the comparison of three means. This is done by the analysis of variance (ANOVA). In this case we will go through an example in detail and work out all the mechanics, but once we have done that and seen how the output is derived from the input we will not need to do it again. We will use R to do the heavy lifting. We will just need to know when it is appropriate to use ANOVA, how to get R to do it and how to interpret the output that R produces.</p>
</section>
<section id="the-scenario" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="the-scenario"><span class="header-section-number">3.1.2</span> The Scenario</h3>
<p>Suppose we have three fertilizers and wish to compare their efficacy. This has been done in a field experiment where each fertilizer is applied to 10 plots and the 30 plots are later harvested, with the crop yields being calculated. We end up with three groups of 10 figures and we wish to know if there are any differences between these groups.</p>
<p>When we plot the data we see that the fertilizers do differ in the amount of yield produced but that there is also a lot of variation between the plots that were given the same fertilizer.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-does-an-anova-do" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="what-does-an-anova-do"><span class="header-section-number">3.1.3</span> What does an ANOVA do?</h3>
<p>An ANOVA (ANalysis Of VAriance) analysis attempts to determine whether the differences between the effect of the fertilizers is significant by investigating the variability in the data. We investigate how the variability <em>between</em> groups compares to the variability <em>within</em> groups.</p>
</section>
<section id="grand-mean" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="grand-mean"><span class="header-section-number">3.1.4</span> Grand Mean</h3>
<p>First we calculate the ‘grand mean’, the mean of the yields across all 30 plots:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.643667</code></pre>
</div>
</div>
<section id="deviations-from-the-grand-mean" class="level4" data-number="3.1.4.1">
<h4 data-number="3.1.4.1" class="anchored" data-anchor-id="deviations-from-the-grand-mean"><span class="header-section-number">3.1.4.1</span> Deviations from the grand mean</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/SST plot-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mean-value-of-yield-for-each-fertilizer" class="level4" data-number="3.1.4.2">
<h4 data-number="3.1.4.2" class="anchored" data-anchor-id="mean-value-of-yield-for-each-fertilizer"><span class="header-section-number">3.1.4.2</span> Mean value of yield for each fertilizer</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  FERTIL fmean
  &lt;fct&gt;  &lt;dbl&gt;
1 1       5.44
2 2       4.00
3 3       4.49</code></pre>
</div>
</div>
</section>
</section>
<section id="measures-of-variability" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="measures-of-variability"><span class="header-section-number">3.1.5</span> Measures of variability</h3>
<section id="sst---total-sum-of-squares" class="level4" data-number="3.1.5.1">
<h4 data-number="3.1.5.1" class="anchored" data-anchor-id="sst---total-sum-of-squares"><span class="header-section-number">3.1.5.1</span> SST - Total sum of squares</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.4449</code></pre>
</div>
</div>
<p>SST is the <strong>total sum of squares.</strong> It is the sum of squares of the deviations of the data around the grand mean. This is a measure of the total variability of the data set.</p>
</section>
<section id="sse---error-sum-of-squares" class="level4" data-number="3.1.5.2">
<h4 data-number="3.1.5.2" class="anchored" data-anchor-id="sse---error-sum-of-squares"><span class="header-section-number">3.1.5.2</span> SSE - Error sum of squares</h4>
<p>SSE is the <strong>error sum of squares</strong>. It is the sum of the squares of the deviations of the data around the three separate group means. This is a measure of the variation between plots that have been given the same fertilizer.</p>
</section>
<section id="ssf---fertilizer-sum-of-squares" class="level4" data-number="3.1.5.3">
<h4 data-number="3.1.5.3" class="anchored" data-anchor-id="ssf---fertilizer-sum-of-squares"><span class="header-section-number">3.1.5.3</span> SSF - Fertilizer sum of squares</h4>
<p>SSF is the <strong>fertilizer sum of squares</strong>. This is the sum of the squares of the deviations of the group means from the grand mean. This is a measure of the variation between plots given different fertilizers.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>When the three group means are fitted, there is an obvious reduction in variability around the three means compared to that around the grand mean, but it is not obvious if the fertilizers have had an effect on yield.</p>
<p>At what point do we decide if the amount of variation explained by fitting the means is significant? By this, we mean, “When is the variability between the group means greater than we would expect by chance alone?</p>
<p>First, we note that SSF and SSE partition between them the total variability in the data:</p>
</section>
</section>
<section id="sst-ssf-sse" class="level3" data-number="3.1.6">
<h3 data-number="3.1.6" class="anchored" data-anchor-id="sst-ssf-sse"><span class="header-section-number">3.1.6</span> SST = SSF + SSE</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.4449</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.82275</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.62215</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.4449</code></pre>
</div>
</div>
<p>So the total variability has been divided into two components. That due to differences between plots given different treatments and that due to differences between plots given the same treatment. Variability must be due to one or other of these components. Separating the total SS into its component SS is known as partitioning the sums of squares.</p>
<p>A comparison of SSF and SSE is going to indicate whether fitting the three fertilizer means accounts for a significant amount of variability.</p>
<p>However, to make a proper comparison, we really need to compare the variability per degree of freedom ie the variance.</p>
</section>
<section id="partitioning-the-degrees-of-freedom" class="level3" data-number="3.1.7">
<h3 data-number="3.1.7" class="anchored" data-anchor-id="partitioning-the-degrees-of-freedom"><span class="header-section-number">3.1.7</span> Partitioning the degrees of freedom</h3>
<p>Every sum of squares (SS) has been calculated using a number of independent pieces of information. In each, case, we call this number the number of degrees of freedom for the SS.</p>
<p>For SST this number is one less than the number of data points <em>n</em>. This is because when we calculate the deviations of each data point around a grand mean there are only <em>n-1</em> of them that are independent, since by definition the sum of these deviations is zero, and so when <em>n-1</em> of them have been calculated, the final one is pre-determined.</p>
<p>Similarly, when we calculate SSF, which measures the deviation of the group means from the grand mean, we have <span class="math inline">\(k\)</span>-1 degrees of freedom, (where in the present example <span class="math inline">\(k\)</span>, the number of treatments, is equal to three) since the deviations must sum to zero, so when <span class="math inline">\(k\)</span>-1 of them have been calculated, the last one is pre-determined.</p>
<p>Finally, SSE, which measure deviation around the group means will have <em>n</em>-<em>k</em> degrees of freedom, since the sum of each of the deviations around one of the group means must sum to zero, and so when all but one of them have been calculated, the final one is pre-determined. There are <span class="math inline">\(k\)</span> group means, so the total degrees of freedom for SSE is <em>n</em>-<em>k</em>.</p>
<p>The degrees of freedom are additive: <span class="math display">\[
df(\text{SST}) = df(\text{SSE}) + df(\text{SSF})
\]</span> Check:</p>
<span class="math display">\[\begin{align*}
df(\text{SST}) &amp;= n-1\\
df(\text{SSE}) &amp;= k-1\\
df(\text{SSF}) &amp;= n-k\\
\therefore df(\text{SSE}) + df(\text{SSF}) &amp;= k-1 + n-k\\
&amp;=n-1\\
&amp;=df(\text{SST})

\end{align*}\]</span>
</section>
<section id="mean-squares" class="level3" data-number="3.1.8">
<h3 data-number="3.1.8" class="anchored" data-anchor-id="mean-squares"><span class="header-section-number">3.1.8</span> Mean Squares</h3>
<p>Now we can calculate the <em>variances</em> which are a measure of the amount of variability per degree of freedom.</p>
<p>In this context, we call them <em>mean squares</em>. To find each one we divided each of the sums of squares (SS) by their corresponding degrees of freedom.</p>
<p>Fertiliser Mean Square (FMS) = SSF / <em>k</em> - 1. This is the variation per <em>df</em> between plots given different fertilisers.</p>
<p>Error Mean Square (EMS) = SSE / <em>n</em> - <em>k</em>. This is the variation per <em>df</em> between plots given the same fertiliser.</p>
<p>Total Mean Square (TMS) = SST / <em>n</em> - 1. This is the total variance per <em>df</em> of the dataset.</p>
<p>Unlike the SS, the MS are not additive. That is, FMS + EMS <span class="math inline">\(\neq\)</span> TMS.</p>
</section>
<section id="f-ratios" class="level3" data-number="3.1.9">
<h3 data-number="3.1.9" class="anchored" data-anchor-id="f-ratios"><span class="header-section-number">3.1.9</span> <em>F</em>-ratios</h3>
<p>If none of the fertilizers influenced yield, we would expect as much variation between the plots treated with the same fertilizer as between the plots treated with different fertilizers.</p>
<p>We can express this in terms of the mean squares: the mean square for fertilizer would be the same as the mean square for error:</p>
<p><span class="math display">\[
\frac{\text{FMS}}{\text{EMS}}=1
\]</span> We call this ratio the <em>F</em>-ratio. It is the end result of ANOVA. <em>F</em>-ratios can never be negative since they are the ratio of two mean square values, both of which must be non-negative, but there is no limit to how large they can be.</p>
<p>Even if the fertilizers were identical, the <em>F</em>-ratio is unlikely to be exactly 1 - it could by chance take a whole range of values. The <strong>F-distribution</strong> represents the range and likelihood of all possible <em>F</em> ratios under the null hypothesis. ie when the fertilizers were identical.</p>
<p>The shape of the F distribution depends on the degrees of freedom of FMS and EMS, and we normally specify it by giving the values of each. Below we show F distributions for 2 and 27 degrees of freedom (ie 3 plots, so <em>k</em> = 3, so the degrees of freedom of FMS = <em>k</em>-1 =2, and 10 plants per plot, so <em>n</em> = 3 x 10 =30, and hence the degrees of freedom of EMS = <em>n</em>-<em>k</em> = 30 - 3 = 27), and for 10 and 27 degrees of freedom.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Note that, whatever the degrees of freedom, <em>F</em>-distributions are examples of so-called probability density functions. The area beneath them between any two values of <em>F</em>-ratio is equal to the probability of getting an <em>F</em>-ratio in that range. Hence the total area under the curves is equal to 1, since the <em>F</em>-ratio must take some value between zero and infinity, and the area under the tail to the right of any given <em>F</em>-ratio is the probability of getting an <em>F</em>-ratio bigger than that value.</p>
<p>Hence, the probability under the null hypothesis of getting an <em>F</em>-ratio as large or larger than the value we actually got is the area to the right of this <em>F</em>-ratio under the appropriate F distribution. We often call this probability the <em>p</em>-value. p for probability. p-values are the the probability of getting data as extreme (same <em>F</em>-ratio,) or more extreme (bigger <em>F</em>-ratio) as the data you got you got if the null hypothesis were true.</p>
<p>If the fertilizers were very different, then the FMS would be much greater than the EMS and the <em>F</em>-ratio would be greater than one. However it can be quite large even when there are no treatment differences. So how do we decide when the size of the <em>F</em>-ratio is due to treatment rather than to chance?</p>
<p>Traditionally, we decide that it sufficiently larger than one to be due to treatment differences if it would be this large or larger under the null hypothesis only 5% or less of the time. If we had inside knowledge that the null hypothesis was in fact true then we would still get an <em>F</em>-ratio that large or larger 5% of the time.</p>
<p>Our <em>p</em>-value ie the probability that the <em>F</em>-ratio would have been as large as it is or larger, under the null hypothesis, represents the strength of evidence against the null hypothesis. The smaller it is, the stronger the evidence, and only when it is less than 0.05 do we regard the evidence as strong enough to reject the null.</p>
</section>
</section>
<section id="anova-example-1" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="anova-example-1"><span class="header-section-number">3.2</span> ANOVA example 1</h2>
<p>We will carry out the ANOVA analysis of the fertilizer data discussed on the previous tab.</p>
<p>Our question is whether yield depends on fertilizer.</p>
<p>What is our null hypothesis?</p>
<p>Start a new notebook with these two code chunks to begin with:</p>
<pre><code>```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, warning=FALSE, message=FALSE,echo=FALSE)
```

```{r load packages, message=FALSE,warning=FALSE,echo=FALSE}
library(tidyverse)
library(here)
library(cowplot)
library(gridExtra)
library(ggfortify)
```</code></pre>
<p>Load the <code>fertilizer.csv</code> data into an object call `fertilizer</p>
<p>Is it tidy data? If not, tidy it.</p>
<p>Convert the FERTIL column to a factor, using this code:</p>
<pre><code>```{r make_factor}
fertilizer &lt;- fertilizer |&gt;
  mutate(FERTIL=as.factor(FERTIL))
```</code></pre>
<p>Make a box plot of yield vs fertilizer, like the one on the previous tab.</p>
<p>Now use the <code>lm()</code> function to create the anova model (There are several ways to do this in R - this is just one)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fertil.model<span class="ot">&lt;-</span><span class="fu">lm</span>(YIELD<span class="sc">~</span>FERTIL,<span class="at">data=</span>fertilizer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now inspect the model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fertil.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: YIELD
          Df Sum Sq Mean Sq F value   Pr(&gt;F)   
FERTIL     2 10.823  5.4114  5.7024 0.008594 **
Residuals 27 25.622  0.9490                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>So we find that we can reject the null hypothesis. There is thus evidence that fertilizer does affect yield (ANOVA, df = 2,27, F=5.7, p&lt; 0.01)</p>
<p>What this test has not done so far is show us where the differences lie. An ANOVA is a holistic test that tells you whether or not there is evidence for a difference between at least one pair of groups being compared. To identify which gruopd, if any, are differeny, we need to do so-called post-hoc tests.</p>
</section>
<section id="anova-example-2" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="anova-example-2"><span class="header-section-number">3.3</span> ANOVA example 2</h2>
<p>An experiment was performed to compare four melon varieties. It was designed so that each variety was grown in six plots, but two plots growing variety 3 were accidentally destroyed.</p>
<p>We wish to find out if there is evidence for a difference in yield between the varieties.</p>
<section id="null-hypothesis" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="null-hypothesis"><span class="header-section-number">3.3.1</span> Null hypothesis</h3>
<p>What is the null hypothesis of this study?</p>
<p>The data are in the <code>melons.csv</code> dataset.</p>
<p>Write code chunks to</p>
</section>
<section id="load-data-and-inspect-the-data" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="load-data-and-inspect-the-data"><span class="header-section-number">3.3.2</span> Load data and inspect the data</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22
Columns: 2
$ YIELDM  &lt;dbl&gt; 25.12, 17.25, 26.42, 16.08, 22.15, 15.92, 40.25, 35.25, 31.98,…
$ VARIETY &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4,…</code></pre>
</div>
</div>
</section>
<section id="prepare-the-data" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="prepare-the-data"><span class="header-section-number">3.3.3</span> Prepare the data</h3>
<p>Ensure that the VARIETY column is a factor</p>
</section>
<section id="plot-the-data" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="plot-the-data"><span class="header-section-number">3.3.4</span> Plot the data</h3>
<p>Create a scatter plot of the yield.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summarise-the-data" class="level3" data-number="3.3.5">
<h3 data-number="3.3.5" class="anchored" data-anchor-id="summarise-the-data"><span class="header-section-number">3.3.5</span> Summarise the data</h3>
<p>Create a summary table that shows the mean yield for each variety.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  VARIETY     N  Mean
  &lt;fct&gt;   &lt;int&gt; &lt;dbl&gt;
1 1           6  20.5
2 2           6  37.4
3 3           4  20.5
4 4           6  29.9</code></pre>
</div>
</div>
</section>
<section id="way-anova" class="level3" data-number="3.3.6">
<h3 data-number="3.3.6" class="anchored" data-anchor-id="way-anova"><span class="header-section-number">3.3.6</span> 1-way ANOVA</h3>
<section id="create-the-model" class="level4" data-number="3.3.6.1">
<h4 data-number="3.3.6.1" class="anchored" data-anchor-id="create-the-model"><span class="header-section-number">3.3.6.1</span> Create the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>melons.model<span class="ot">&lt;-</span><span class="fu">lm</span>(YIELDM<span class="sc">~</span>VARIETY,<span class="at">data=</span>melons)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="check-the-validity-of-the-model" class="level4" data-number="3.3.6.2">
<h4 data-number="3.3.6.2" class="anchored" data-anchor-id="check-the-validity-of-the-model"><span class="header-section-number">3.3.6.2</span> Check the validity of the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(melons.model,<span class="at">smooth.colour=</span><span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>DO the data look as though they meet the criteria for an ANOVA? - the variance of the residuals is roughly constant across all groups and the qq-plot is fairly straight. We could confirm with a normality test if we like. For example, we could use a Shapiro-Wilk test.</p>
<p>What is the null hypothesis of this test?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(melons.model<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  melons.model$residuals
W = 0.94567, p-value = 0.2586</code></pre>
</div>
</div>
<p>What do we conclude from this test?</p>
</section>
<section id="inspect-the-model" class="level4" data-number="3.3.6.3">
<h4 data-number="3.3.6.3" class="anchored" data-anchor-id="inspect-the-model"><span class="header-section-number">3.3.6.3</span> Inspect the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(melons.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: YIELDM
          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
VARIETY    3 1115.28  371.76  23.798 1.735e-06 ***
Residuals 18  281.19   15.62                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>What conclusions would you draw from the output of this model and the table of mean yields for each variety?</p>
</section>
</section>
<section id="confidence-intervals-of-the-means" class="level3" data-number="3.3.7">
<h3 data-number="3.3.7" class="anchored" data-anchor-id="confidence-intervals-of-the-means"><span class="header-section-number">3.3.7</span> Confidence intervals of the means</h3>
<p>Let us find the 95% confidence intervals for each mean</p>
<p>These we calculate as</p>
<p><span class="math display">\[
\text{Mean}\pm t_{\text{crit}}\text{SE}_{\text{mean}}
\]</span> For a 95% confidence interval and 18 degrees of freedom, <span class="math inline">\(t_{\text{crit}}\)</span> is 2.1, so we find that the intervals are:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  VARIETY  Mean    LB    UB
  &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 1        20.5  17.1  23.9
2 2        37.4  34.0  40.8
3 3        20.5  16.3  24.6
4 4        29.9  26.5  33.3</code></pre>
</div>
</div>
</section>
</section>
<section id="anova-example-2-solution" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="anova-example-2-solution"><span class="header-section-number">3.4</span> ANOVA example 2 solution</h2>
<p>An experiment was performed to compare four melon varieties. It was designed so that each variety was grown in six plots, but two plots growing variety 3 were accidentally destroyed.</p>
<p>We wish to find out if there is evidence for a difference in yield between the varieties.</p>
<section id="null-hypothesis-1" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="null-hypothesis-1"><span class="header-section-number">3.4.1</span> Null hypothesis</h3>
<p>What is the null hypothesis of this study?</p>
<p>The data are in the <code>melons.csv</code> dataset.</p>
<p>Write code chunks to</p>
</section>
<section id="load-data-and-inspect-the-data-1" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="load-data-and-inspect-the-data-1"><span class="header-section-number">3.4.2</span> Load data and inspect the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>filepath<span class="ot">&lt;-</span><span class="fu">here</span>(<span class="st">"data"</span>,<span class="st">"melons.csv"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>melons<span class="ot">&lt;-</span><span class="fu">read_csv</span>(filepath)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(melons)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22
Columns: 2
$ YIELDM  &lt;dbl&gt; 25.12, 17.25, 26.42, 16.08, 22.15, 15.92, 40.25, 35.25, 31.98,…
$ VARIETY &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4,…</code></pre>
</div>
</div>
</section>
<section id="prepare-the-data-1" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="prepare-the-data-1"><span class="header-section-number">3.4.3</span> Prepare the data</h3>
<p>Ensure that the VARIETY column is a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>melons <span class="ot">&lt;-</span> melons <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">VARIETY=</span><span class="fu">as.factor</span>(VARIETY))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-the-data-1" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="plot-the-data-1"><span class="header-section-number">3.4.4</span> Plot the data</h3>
<p>Create a scatter plot of the yield.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>melons <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>VARIETY,<span class="at">y=</span>YIELDM)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">45</span>),<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">45</span>,<span class="dv">5</span>))<span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Melon variety"</span>, <span class="at">y=</span><span class="st">"Yield"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summarise-the-data-1" class="level3" data-number="3.4.5">
<h3 data-number="3.4.5" class="anchored" data-anchor-id="summarise-the-data-1"><span class="header-section-number">3.4.5</span> Summarise the data</h3>
<p>Create a summary table that shows the mean yield for each variety.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>melons <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VARIETY) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">N=</span><span class="fu">n</span>(),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean=</span><span class="fu">round</span>(<span class="fu">mean</span>(YIELDM),<span class="dv">2</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  VARIETY     N  Mean
  &lt;fct&gt;   &lt;int&gt; &lt;dbl&gt;
1 1           6  20.5
2 2           6  37.4
3 3           4  20.5
4 4           6  29.9</code></pre>
</div>
</div>
</section>
<section id="way-anova-1" class="level3" data-number="3.4.6">
<h3 data-number="3.4.6" class="anchored" data-anchor-id="way-anova-1"><span class="header-section-number">3.4.6</span> 1-way ANOVA</h3>
<section id="create-the-model-1" class="level4" data-number="3.4.6.1">
<h4 data-number="3.4.6.1" class="anchored" data-anchor-id="create-the-model-1"><span class="header-section-number">3.4.6.1</span> Create the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>melons.model<span class="ot">&lt;-</span><span class="fu">lm</span>(YIELDM<span class="sc">~</span>VARIETY,<span class="at">data=</span>melons)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="check-the-validity-of-the-model-1" class="level4" data-number="3.4.6.2">
<h4 data-number="3.4.6.2" class="anchored" data-anchor-id="check-the-validity-of-the-model-1"><span class="header-section-number">3.4.6.2</span> Check the validity of the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(melons.model,<span class="at">smooth.colour=</span><span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">theme_cowplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ANOVA_how_it_works_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>The data look as though they meet the criteria for an ANOVA - the variance of the residuals is roughly constant across all groups and the qq-plot is fairly straight. We could confirm with a normality test if we like. For example, we could use a Shapiro-Wilk test.</p>
<p>The null hypothesis of this test is that the residuals are drawn from a population that is normally distributed</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(melons.model<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  melons.model$residuals
W = 0.94567, p-value = 0.2586</code></pre>
</div>
</div>
<p>Since <em>p</em>&gt;0.05 we conclude that there is no reason to reject the null hypothesis that the residuals are normally disributed.</p>
</section>
<section id="inspect-the-model-1" class="level4" data-number="3.4.6.3">
<h4 data-number="3.4.6.3" class="anchored" data-anchor-id="inspect-the-model-1"><span class="header-section-number">3.4.6.3</span> Inspect the model</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(melons.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: YIELDM
          Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
VARIETY    3 1115.28  371.76  23.798 1.735e-06 ***
Residuals 18  281.19   15.62                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(melons.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = YIELDM ~ VARIETY, data = melons)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.4233 -2.2781 -0.5933  2.6694  5.9300 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20.4900     1.6136  12.699 2.02e-10 ***
VARIETY2     16.9133     2.2819   7.412 7.14e-07 ***
VARIETY3     -0.0275     2.5513  -0.011  0.99152    
VARIETY4      9.4067     2.2819   4.122  0.00064 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.952 on 18 degrees of freedom
Multiple R-squared:  0.7986,    Adjusted R-squared:  0.7651 
F-statistic:  23.8 on 3 and 18 DF,  p-value: 1.735e-06</code></pre>
</div>
</div>
<p>What conclusions would you draw from the output of this model and the table of mean yields for each variety?</p>
<p>We see that the null hypothesis is rejected with a <em>p</em>-value of less than 0.001. We conclude that there are significant differences in the mean yield of melons across the varieties. We estimate that variety 2 has the highest mean yield and varieties 1 and 3 have the lowest mean yields.</p>
<p>The unexplained variance ie the error <em>s</em> for each group is 15.6 with 18 degrees of freedom. So the standard error for each group is <span class="math inline">\(\frac{s}{\sqrt{n}}\)</span> where s=<span class="math inline">\(\sqrt{15.6}\)</span> = 3.95 divided by the number of elements in each group, giving us standard errors of 1.97 for variety 3, and 1.61 for the other varieties.</p>
</section>
</section>
<section id="confidence-intervals-of-the-means-1" class="level3" data-number="3.4.7">
<h3 data-number="3.4.7" class="anchored" data-anchor-id="confidence-intervals-of-the-means-1"><span class="header-section-number">3.4.7</span> Confidence intervals of the means</h3>
<p>Let us find the 95% confidence intervals for each mean</p>
<p>These we calculate as</p>
<p><span class="math display">\[
\text{Mean}\pm t_{\text{crit}}\text{SE}_{\text{mean}}
\]</span> For a 95% confidence interval and 18 degrees of freedom, <span class="math inline">\(t_{\text{crit}}\)</span> is 2.1, so we find that the intervals are:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  VARIETY  Mean    LB    UB
  &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 1        20.5  17.1  23.9
2 2        37.4  34.0  40.8
3 3        20.5  16.3  24.6
4 4        29.9  26.5  33.3</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./workflow.html" class="pagination-link" aria-label="A recommended analysis workflow">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A recommended analysis workflow</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>CC-BY-SA-4.0 (2025) Michael Hunt</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>